src/Family/Bundle/TreeBundle/Entity/Person.php
<?php

namespace Family\Bundle\TreeBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Person
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Family\Bundle\TreeBundle\Entity\PersonRepository")
 */
class Person
{

    const SEX_M = 'M';
    const SEX_F = 'F';

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="firstName", type="string", length=255, nullable=true)
     */
    private $firstName;

    /**
     * @var string
     *
     * @ORM\Column(name="middleNames", type="string", length=255, nullable=true)
     */
    private $middleNames;

    /**
     * @var string
     *
     * @ORM\Column(name="lastName", type="string", length=255, nullable=true)
     */
    private $lastName;

    /**
     * @var string
     *
     * @ORM\Column(name="surName", type="string", length=255, nullable=true)
     */
    private $surName;

    /**
     * @var string
     *
     * @ORM\Column(name="sex", type="string", length=1, nullable=true)
     */
    private $sex;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="birthDate", type="date", nullable=true)
     */
    private $birthDate;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="deathDate", type="date", nullable=true)
     */
    private $deathDate;

    /**
     * @ORM\OneToMany(targetEntity="Family\Bundle\TreeBundle\Entity\Relation", mappedBy="firstPerson", cascade={"persist", "remove"})
     */
    private $firstPartRelations; 

    /**
     * @ORM\OneToMany(targetEntity="Family\Bundle\TreeBundle\Entity\Relation", mappedBy="secondPerson", cascade={"persist", "remove"})
     */
    private $secondPartRelations; 
    
    /**
     * @ORM\ManyToOne(targetEntity="Family\Bundle\TreeBundle\Entity\Relation", inversedBy="children", cascade={"persist"})
     * @ORM\JoinColumn(nullable=true)
     */
    private $parentsRelation;
    
    /**
     * @ORM\ManyToOne(targetEntity="Family\Bundle\TreeBundle\Entity\Family", inversedBy="persons", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $family;

    /**
     * @ORM\OneToMany(targetEntity="Family\Bundle\TreeBundle\Entity\Document", mappedBy="person", cascade={"persist", "remove"})
     */
    private $documents; 

    /**
     * @var text
     *
     * @ORM\Column(name="notes", type="text", nullable=true)
     */
    private $notes;

    /**
     * @ORM\OneToOne(targetEntity="Family\Bundle\UserBundle\Entity\User", mappedBy="person")
     * @ORM\JoinColumn(nullable=true)
     */
    private $user;





    public function __construct()
    {
        $this->birthDate = null;
        $this->deathDate = null;
        $this->firstPartRelations = new \Doctrine\Common\Collections\ArrayCollection();
        $this->secondPartRelations = new \Doctrine\Common\Collections\ArrayCollection();
        $this->parentsRelation = null;
    }





    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set firstName
     *
     * @param string $firstName
     * @return Person
     */
    public function setFirstName($firstName)
    {
        $this->firstName = $firstName;

        return $this;
    }

    /**
     * Get firstName
     *
     * @return string 
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * Set middleNames
     *
     * @param string $middleNames
     * @return Person
     */
    public function setMiddleNames($middleNames)
    {
        $this->middleNames = $middleNames;

        return $this;
    }

    /**
     * Get middleNames
     *
     * @return string 
     */
    public function getMiddleNames()
    {
        return $this->middleNames;
    }

    /**
     * Set lastName
     *
     * @param string $lastName
     * @return Person
     */
    public function setLastName($lastName)
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * Get lastName
     *
     * @return string 
     */
    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * Set surName
     *
     * @param string $surName
     * @return Person
     */
    public function setSurName($surName)
    {
        $this->surName = $surName;

        return $this;
    }

    /**
     * Get surName
     *
     * @return string 
     */
    public function getSurName()
    {
        return $this->surName;
    }

    /**
     * Get surName
     *
     * @return string 
     */
    public function getFullName()
    {
        $fullName = $this->getFirstName() . ' ';
        if ($this->surName != null)
            $fullName .= '"' . $this->surName . '" ';
        if ($this->middleNames != null)
            $fullName .= $this->middleNames . ' ';
        $fullName = $fullName . $this->getLastName();

        if ($this->birthDate or $this->deathDate) {
            $birthDate = " -";
            $deathDate = "- ";
            if ($this->birthDate)
                $birthDate = $this->birthDate->format("d/m/Y");
            if ($this->deathDate)
                $deathDate = $this->deathDate->format("d/m/Y");
                $fullName .= " (" . $birthDate . " | " . $deathDate . ")";
        }
        return $fullName;
    }

    /**
     * Set sex
     *
     * @param string $sex
     * @return Person
     */
    public function setSex($sex)
    {
        if (!in_array($sex, array(self::SEX_M, self::SEX_F))) {
            throw new \InvalidArgumentException("Invalid sex parameter.");
        }
        $this->sex = $sex;

        return $this;
    }


    /**
     * Get sex
     *
     * @return string 
     */
    public function getSex()
    {
        return $this->sex;
    }

    /**
     * Set birthDate
     *
     * @param \DateTime $birthDate
     * @return Person
     */
    public function setBirthDate($birthDate)
    {
        if ( $birthDate >= new \DateTime("now") ) {
            throw new \InvalidArgumentException("BirthDate can't be in the future : " . $this->birthDate->format("d/m/Y"));
        }
        $this->birthDate = $birthDate;

        return $this;
    }

    /**
     * Get birthDate
     *
     * @return \DateTime 
     */
    public function getBirthDate()
    {
        return $this->birthDate;
    }

    /**
     * Set deathDate
     *
     * @param \DateTime $deathDate
     * @return Person
     */
    public function setDeathDate($deathDate)
    {
        if ( $deathDate >= new \DateTime("now")) {
            throw new \InvalidArgumentException("Death date can't be in the future.");
        }
        $this->deathDate = $deathDate;

        return $this;
    }

    /**
     * Get deathDate
     *
     * @return \DateTime 
     */
    public function getDeathDate()
    {
        return $this->deathDate;
    }

    public function addRelation(\Family\Bundle\TreeBundle\Entity\Relation $relation)
    {
        return $this;
    }

    public function removeRelation(\Family\Bundle\TreeBundle\Entity\Relation $relation)
    {
        if ($this->firstPartRelations->contains($relation)) {
            $this->removeFirstPartRelation($relation);
        } else if ($this->secondPartRelations->contains($relation)) {
            $this->removeSecondPartRelation($relation);
        }
    }

    public function addFirstPartRelation(\Family\Bundle\TreeBundle\Entity\Relation $firstPartRelation)
    {
        $this->firstPartRelations[] = $firstPartRelation;
        $firstPartRelation->setFirstPerson($this); 
        return $this;
    }

    public function removeFirstPartRelation(\Family\Bundle\TreeBundle\Entity\Relation $firstPartRelation)
    {
        print_r("removeFirstPartRelation");
        $this->firstPartRelations->removeElement($firstPartRelation);
        $firstPartRelation->setFirstPerson(null);
    }

    /**
     * Get firstPartRelations
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getFirstPartRelations()
    {
        return $this->firstPartRelations;
    }

    public function addSecondPartRelation(\Family\Bundle\TreeBundle\Entity\Relation $secondPartRelation)
    {
        $this->secondPartRelations[] = $secondPartRelation;
        $secondPartRelation->setSecondPerson($this); 
        return $this;
    }

    public function removeSecondPartRelation(\Family\Bundle\TreeBundle\Entity\Relation $secondPartRelation)
    {
        print_r("removeSecondPartRelation");
        $this->secondPartRelations->removeElement($secondPartRelation);
        $secondPartRelation->setSecondPerson(null);
    }

    /**
     * Get secondPartRelations
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getSecondPartRelations()
    {
        return $this->secondPartRelations;
    }

    /**
     * Set parentsRelation
     *
     * @param \Family\Bundle\TreeBundle\Entity\Relation $parentsRelation
     * @return Person
     */
    public function setParentsRelation(\Family\Bundle\TreeBundle\Entity\Relation $parentsRelation)
    {
        $this->parentsRelation = $parentsRelation;

        return $this;
    }

    /**
     * Get parentsRelation
     *
     * @return \Family\Bundle\TreeBundle\Entity\Relation 
     */
    public function getParentsRelation()
    {
        return $this->parentsRelation;
    }

    /**
     * Set family
     *
     * @param \Family\Bundle\TreeBundle\Entity\Family $family
     * @return Person
     */
    public function setFamily(\Family\Bundle\TreeBundle\Entity\Family $family)
    {
        $this->family = $family;

        return $this;
    }

    /**
     * Get family
     *
     * @return \Family\Bundle\TreeBundle\Entity\Family 
     */
    public function getFamily()
    {
        return $this->family;
    }

    public function getRelations()
    {

src/Family/Bundle/TreeBundle/Resources/views/Tree/allChildren.html.twig
{% for child in relation.children %}

	<div id="pers-{{ child.id }}" class="element {% if child.sex == "F" %}fe{% endif %}male">
		{% include 'FamilyTreeBundle:Tree:personCard.html.twig' with {'person': child} only %}
	</div>

	{% for rel in child.relations %}

		{% include 'FamilyTreeBundle:Tree:unionCard.html.twig' with {'relation': rel} only %}

		{% if rel.firstPerson.id == child.id %}
			{% set pers = rel.secondPerson %}
		{% else %}
			{% set pers = rel.firstPerson %}
		{% endif %}

		<div id="pers-{{ pers.id }}" class="element {% if pers.sex == "F" %}fe{% endif %}male">
			{% include 'FamilyTreeBundle:Tree:personCard.html.twig' with {'person': pers} only %}
		</div>

	{% endfor %}

{% endfor %}

<br>

{% for child in relation.children %}
	<div class="blocks">
		{% for relation in child.relations %}
			{% include 'FamilyTreeBundle:Tree:allChildren.html.twig' with {'relation': relation} only %}
		{% endfor %}
	</div>
{% endfor %}

src/Family/Bundle/TreeBundle/Resources/views/Tree/allChildrenRelationLinks.html.twig
{% for child in relation.children %}
	jsPlumb.connect({ source: "rel-{{ relation.id }}", target:"pers-{{ child.id }}" }, children);
	{% for rel in child.relations %}
		{% if rel.firstPerson.id == child.id %}
			{% set pers = rel.secondPerson %}
		{% else %}
			{% set pers = rel.firstPerson %}
		{% endif %}
		jsPlumb.connect({ source: "rel-{{ rel.id }}", target:"pers-{{ child.id }}" }, marriedLeft);
		jsPlumb.connect({ source: "pers-{{ pers.id }}", target:"rel-{{ rel.id }}" }, marriedRight);

		{{ render(controller('FamilyTreeBundle:Default:getAllChildrenRelationLinks', { 'relationId': rel.id })) }}
	{% endfor %}
{% endfor %}

src/Family/Bundle/TreeBundle/Resources/views/Tree/parents.html.twig
{% set firstP = relation.firstPerson %}
{% set secondP = relation.secondPerson %}

{% if firstP.parentsRelation %}
	<div class="blocks">
		{% include 'FamilyTreeBundle:Tree:parents.html.twig' with {'relation': firstP.parentsRelation} only %}
	</div>
{% endif %}

{% if secondP.parentsRelation %}
	<div class="blocks">
		{% include 'FamilyTreeBundle:Tree:parents.html.twig' with {'relation': secondP.parentsRelation} only %}
	</div>
{% endif %}
	<br/>

<div id="pers-{{ firstP.id }}" class="element {% if firstP.sex == "F" %}fe{% endif %}male">
	{% include 'FamilyTreeBundle:Tree:personCard.html.twig' with {'person': firstP} only %}
</div>

{% include 'FamilyTreeBundle:Tree:unionCard.html.twig' with {'relation': relation} only %}

<div id="pers-{{ secondP.id }}" class="element {% if secondP.sex == "F" %}fe{% endif %}male">
	{% include 'FamilyTreeBundle:Tree:personCard.html.twig' with {'person': secondP} only %}
</div>

src/Family/Bundle/TreeBundle/Resources/views/Tree/parentsRelationLinks.html.twig
jsPlumb.connect({ source: "rel-{{ relation.id }}", target:"pers-{{ relation.firstPerson.id }}" }, marriedLeft);
jsPlumb.connect({ source: "pers-{{ relation.secondPerson.id }}", target:"rel-{{ relation.id }}" }, marriedRight);
jsPlumb.connect({ source: "rel-{{ relation.id }}", target:"pers-{{ child.id }}" }, children);

{% if relation.firstPerson.parentsRelation %}
	{% include 'FamilyTreeBundle:Tree:parentsRelationLinks.html.twig' 
		with {'relation': relation.firstPerson.parentsRelation, 'child': relation.firstPerson} only %}
{% endif %}

{% if relation.secondPerson.parentsRelation %}
	{% include 'FamilyTreeBundle:Tree:parentsRelationLinks.html.twig' 
		with {'relation': relation.secondPerson.parentsRelation, 'child': relation.secondPerson} only %}
{% endif %}

src/Family/Bundle/TreeBundle/Resources/views/Tree/tree.html.twig
<!doctype html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<title>Arbre</title>
</head>
<body>	
	
	<style>
		div {
			vertical-align: top;
		}
		#container {
			text-align: center;
			overflow: scroll;
			width: 3000px;
		}
		.blocks {
			display: inline-block;
		}
		.element {
			margin: 20px;
			margin-top: 0px;
			padding: 5px;
			display: inline-block;
			height: 150px;
			width: 120px;
			text-align: left;
		}
		.element.male {
			background-color: #6688FF;
		}
		.element.female {
			background-color: #FF8866;
		}
		.union {
			display: inline-block;
			margin-top: 61px;
			margin-bottom: 100px;
 		}
		.element .photo {
			height: 75px;
			width: 75px;
			background-color: #fff;
			display: inline-block;
			margin-left: auto;
			margin-right: auto;
		}
	/*
		#container {
			margin: 20px;
			text-align: center;
			overflow: scroll;
			width: 3000px;
			vertical-align: top;
		}
		#container>.blocks {
			display: inline-block;
			text-align: center;
			vertical-align: top;
		}
		.element {
			margin: 20px;
			padding: 5px;
			display: inline-block;
			height: 150px;
			min-width: 100px;
		}
		.element.male {
			background-color: #6688FF;
		}
		.element.female {
			background-color: #FF8866;
		}
		.element .photo {
			height: 60px;
			width: 50px;
			background-color: #fff;
			display: inline-block;
		}
		.union {
			display: inline-block;
			height: 150px;
		}
	*/
	</style>

	<div id="container">
		<div class="blocks">
			<div id="pers-{{ people.id }}" class="element {% if (people.sex == "F") %}fe{% endif %}male">
				<div class="person">
					<div class="photo"></div>
					<div class="name">{{ people.firstName }} {{ people.lastName }}</div>
					<div class="birthDate">N : {{ people.birthDate | date("d/m/Y") }}</div>
					<div class="deathDate">M : {{ people.deathDate | date("d/m/Y") | default(' - ') }}</div>
				</div>
			</div>
			{% for relation in people.relations %}
				<div id="rel-{{ relation.id }}" class="union">
					<div class="marriage">
						<div class="logo">Mariage</div>
						<div class="date">{{ relation.start | date("d/m/Y") | default(' - ') }}</div>
					</div>
				</div>

				<div id="pers-{{ relation.secondPerson.id }}" class="element {% if relation.secondPerson.sex == "F" %}fe{% endif %}male">
					<div class="person">
						<div class="photo"></div>
						<div class="name">{{ relation.secondPerson.firstName }} {{ relation.secondPerson.lastName }}</div>
						<div class="birthDate">N : {{ relation.secondPerson.birthDate | date("d/m/Y") }}</div>
						<div class="deathDate">M : {{ relation.secondPerson.deathDate | date("d/m/Y") | default(' - ') }}</div>
					</div>
				</div>

				<br>

				<div class="blocks">
					{% for child in relation.children %}
						<div id="pers-{{ child.id }}" class="element {% if child.sex == "F" %}fe{% endif %}male">
							<div class="child">
								<div class="photo"></div>
								<div class="name">{{ child.firstName }} {{ child.lastName }}</div>
								<div class="birthDate">N : {{ child.birthDate | date("d/m/Y") }}</div>
								<div class="deathDate">M : {{ child.deathDate | date("d/m/Y") | default(' - ') }}</div>
							</div>
						</div>
					{% endfor %}
				</div>
			{% endfor %}	
			<br>
			
		</div>
	</div>

	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
	<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"></script>
	<script src="{{ asset('js/jquery.jsplumb-min.js') }}"></script>

	<script>
		jsPlumb.ready(function() {

			var married = {
				anchors:[ "LeftMiddle", "RightMiddle" ],
				paintStyle:{ lineWidth:2, strokeStyle:"#000000" },
				endpoint:"Blank",
				connector:"Straight"
			};
			var children = {
				anchors:[ "BottomCenter", "TopCenter" ],
				paintStyle:{ lineWidth:2, strokeStyle:"#000000" },
				endpoint:"Blank",
				connector:[ "Flowchart", { midpoint:0.8, stub:10, cornerRadius: 15 } ]
			};
			var childrenoverlap = {
				anchors:[ "BottomCenter", "TopCenter" ],
				paintStyle:{ lineWidth:2, strokeStyle:"#000000", outlineColor:"#eeeeee", outlineWidth:4 },
				endpoint:"Blank",
				connector:[ "Flowchart", { stub:13.333333333333 } ]
			};
			var related = {
				anchors:[ "BottomCenter", "TopCenter" ],
				paintStyle:{ lineWidth:2, strokeStyle:"#000000", outlineColor:"#eeeeee", outlineWidth:4 },
				endpoint:"Blank",
				connector:[ "Flowchart", { stub:13.333333333333 } ]
			};
			var related2 = {
				anchors:[ "TopCenter", "TopCenter" ],
				paintStyle:{ lineWidth:2, dashstyle:"4 2", strokeStyle:"#000000", outlineColor:"#eeeeee", outlineWidth:4 },
				endpoint:"Blank",
				connector:[ "Flowchart", { stub:13.333333333333 } ]
			};
			var siblings = {
				anchors:[ "TopCenter", "TopCenter" ],
				paintStyle:{ lineWidth:2, strokeStyle:"#000000", outlineColor:"#eeeeee", outlineWidth:4 },
				endpoint:"Blank",
				connector:[ "Flowchart", { stub:13.333333333333 } ]
			};

			{% for relation in people.relations %}
				jsPlumb.connect({ source: "rel-{{ relation.id }}", target:"pers-{{ relation.firstPerson.id }}" }, married);
				jsPlumb.connect({ source: "pers-{{ relation.secondPerson.id }}", target:"rel-{{ relation.id }}" }, married);
				{% for child in relation.children %}
					jsPlumb.connect({ source: "rel-{{ relation.id }}", target:"pers-{{ child.id }}" }, children);
				{% endfor %}

			{% endfor %}

		});
	</script>
	
</body>
</html>

src/Family/Bundle/TreeBundle/Resources/views/Tree/treeAsc.html.twig
{% extends 'FamilyTreeBundle:Default:layout.html.twig' %}

{% block treeContainer %}


{# Arbre Généalogique Descendant #}

<div id="container">
	<div class="blocks">

		{% if person.parentsRelation %}
			<div class="blocks">
				{% include 'FamilyTreeBundle:Tree:parents.html.twig' with {'relation': person.parentsRelation} only %}
			</div>
		{% endif %}

		<br>

		<div id="pers-{{ person.id }}" class="element {% if person.sex == "F" %}fe{% endif %}male">
			{% include 'FamilyTreeBundle:Tree:personCard.html.twig' with {'person': person} only %}
		</div>

		{% for rel in person.relations %}
			{% include 'FamilyTreeBundle:Tree:unionCard.html.twig' with {'relation': rel} only %}

			{% if rel.firstPerson.id == person.id %}
				{% set pers = rel.secondPerson %}
			{% else %}
				{% set pers = rel.firstPerson %}
			{% endif %}

			<div id="pers-{{ pers.id }}" class="element {% if pers.sex == "F" %}fe{% endif %}male">
				{% include 'FamilyTreeBundle:Tree:personCard.html.twig' with {'person': pers} only %}
			</div>
		{% endfor %}		
		
	</div>
</div>

{% endblock %}


{% block javascripts %}
{{ parent() }}
	<script src="{{ asset('js/jquery.min.js') }}"></script>
	<script src="{{ asset('js/jquery-ui.min.js') }}"></script>
	<script src="{{ asset('js/jquery.jsplumb-min.js') }}"></script>

<script type="text/javascript">
	jsPlumb.ready(function() {

		var marriedLeft = {
			anchors:[ "Center", "Right" ],
			paintStyle:{ lineWidth:2, strokeStyle:"#666666" },
			endpoint:"Blank",
			connector:"Straight"
		};
		var marriedRight = {
			anchors:[ "Left", "Center" ],
			paintStyle:{ lineWidth:2, strokeStyle:"#666666" },
			endpoint:"Blank",
			connector:"Straight"
		};
		var children = {
			anchors:[ "BottomCenter", "TopCenter" ],
			paintStyle:{ lineWidth:2, strokeStyle:"#666666" },
			endpoint:"Blank",
			connector:[ "Flowchart", { midpoint:0.8, stub:10, cornerRadius: 15 } ]
		};

		{% for rel in person.relations %}
			{% if rel.firstPerson.id == person.id %}
				{% set pers = rel.secondPerson %}
			{% else %}
				{% set pers = rel.firstPerson %}
			{% endif %}
			jsPlumb.connect({ source: "rel-{{ rel.id }}", target:"pers-{{ person.id }}" }, marriedLeft);
			jsPlumb.connect({ source: "pers-{{ pers.id }}", target:"rel-{{ rel.id }}" }, marriedRight);
		{% endfor %}

		{% if person.parentsRelation %}
			{% include 'FamilyTreeBundle:Tree:parentsRelationLinks.html.twig' 
				with {'relation': person.parentsRelation, 'child': person} only %}
		{% endif %}

	});
</script>
{% endblock %}

src/Family/Bundle/TreeBundle/Resources/views/Tree/treeDesc.html.twig
{% extends 'FamilyTreeBundle:Default:layout.html.twig' %}

{% block treeContainer %}


{# Arbre Généalogique Descendant #}

<div id="container">
	<div class="blocks">

		<div id="pers-{{ person.id }}" class="element {% if person.sex == "F" %}fe{% endif %}male">
			{% include 'FamilyTreeBundle:Tree:personCard.html.twig' with {'person': person} only %}
		</div>

		{% for rel in person.relations %}
			{% include 'FamilyTreeBundle:Tree:unionCard.html.twig' with {'relation': rel} only %}

			{% if rel.firstPerson.id == person.id %}
				{% set pers = rel.secondPerson %}
			{% else %}
				{% set pers = rel.firstPerson %}
			{% endif %}

			<div id="pers-{{ pers.id }}" class="element {% if pers.sex == "F" %}fe{% endif %}male">
				{% include 'FamilyTreeBundle:Tree:personCard.html.twig' with {'person': pers} only %}
			</div>
		{% endfor %}

		<br>
		
		<div class="blocks">
			{% for relation in person.relations %}
				{% include 'FamilyTreeBundle:Tree:allChildren.html.twig' with {'relation': relation} only %}
			{% endfor %}
		</div>
		
	</div>
</div>

{% endblock %}


{% block javascripts %}
{{ parent() }}
	<script src="{{ asset('js/jquery.min.js') }}"></script>
	<script src="{{ asset('js/jquery-ui.min.js') }}"></script>
	<script src="{{ asset('js/jquery.jsplumb-min.js') }}"></script>

<script type="text/javascript">
	jsPlumb.ready(function() {

		var marriedLeft = {
			anchors:[ "Center", "Right" ],
			paintStyle:{ lineWidth:2, strokeStyle:"#666666" },
			endpoint:"Blank",
			connector:"Straight"
		};
		var marriedRight = {
			anchors:[ "Left", "Center" ],
			paintStyle:{ lineWidth:2, strokeStyle:"#666666" },
			endpoint:"Blank",
			connector:"Straight"
		};
		var children = {
			anchors:[ "BottomCenter", "TopCenter" ],
			paintStyle:{ lineWidth:2, strokeStyle:"#666666" },
			endpoint:"Blank",
			connector:[ "Flowchart", { midpoint:0.8, stub:10, cornerRadius: 15 } ]
		};
		{#var childrenoverlap = {
			anchors:[ "BottomCenter", "TopCenter" ],
			paintStyle:{ lineWidth:2, strokeStyle:"#000000", outlineColor:"#eeeeee", outlineWidth:4 },
			endpoint:"Blank",
			connector:[ "Flowchart", { stub:13.333333333333 } ]
		};
		var related = {
			anchors:[ "BottomCenter", "TopCenter" ],
			paintStyle:{ lineWidth:2, strokeStyle:"#000000", outlineColor:"#eeeeee", outlineWidth:4 },
			endpoint:"Blank",
			connector:[ "Flowchart", { stub:13.333333333333 } ]
		};
		var related2 = {
			anchors:[ "TopCenter", "TopCenter" ],
			paintStyle:{ lineWidth:2, dashstyle:"4 2", strokeStyle:"#000000", outlineColor:"#eeeeee", outlineWidth:4 },
			endpoint:"Blank",
			connector:[ "Flowchart", { stub:13.333333333333 } ]
		};
		var siblings = {
			anchors:[ "TopCenter", "TopCenter" ],
			paintStyle:{ lineWidth:2, strokeStyle:"#000000", outlineColor:"#eeeeee", outlineWidth:4 },
			endpoint:"Blank",
			connector:[ "Flowchart", { stub:13.333333333333 } ]
		};#}

		{% for rel in person.relations %}
			{% if rel.firstPerson.id == person.id %}
				{% set pers = rel.secondPerson %}
			{% else %}
				{% set pers = rel.firstPerson %}
			{% endif %}
			jsPlumb.connect({ source: "rel-{{ rel.id }}", target:"pers-{{ person.id }}" }, marriedLeft);
			jsPlumb.connect({ source: "pers-{{ pers.id }}", target:"rel-{{ rel.id }}" }, marriedRight);
		{% endfor %}

		{% for relation in person.relations %}
			{% include 'FamilyTreeBundle:Tree:allChildrenRelationLinks.html.twig' with {'relation': relation} only %}
		{% endfor %}
	});
</script>
{% endblock %}